# --- Imports & Constants ---

from __future__ import annotations
from typing import Dict, Any
from langchain_core.prompts import ChatPromptTemplate
import json
import re
from loguru import logger
from pydantic import ValidationError
from aiminer.app_workflow.state import AlphaMinerState
from aiminer.core.llm import get_llm
from aiminer.schemas.messages import FormalizationOutput, ImplementationOutput


class FactorAgent:
    """
    FactorAgent translates the market hypothesis into executable code (Formalization and Implementation).
    """

# --- Operator Whitelist & Signatures ---

    # Verified Whitelist of supported Qlib operators in our Matrix Engine (rq_eval.py)
    QLIB_OPERATORS = {
        # Cross-sectional
        "Rank",
        "CSRank",
        "CSZScore",
        "GroupNeutral",
        "Winsorize",
        "Percentile",
        "Scale",
        # Time-series
        "Mean",
        "Std",
        "Med",
        "Median",
        "EMA",
        "WMA",
        "Sum",
        "Ref",
        "Delta",
        "Ts_Rank",
        "Ts_Max",
        "Ts_Min",
        "Ts_ArgMax",
        "Ts_ArgMin",
        "Ts_Percentile",
        # Correlation / covariance
        "Corr",
        "Correlation",
        "Cov",
        # Math unary
        "Abs",
        "Log",
        "Sign",
        "Sqrt",
        "Exp",
        "Neg",
        "Inv",
        "Ceil",
        "Floor",
        # Math binary / aliases
        "Add",
        "Sub",
        "Mul",
        "Div",
        "Mult",
        "Divi",
        "Plus",
        "Minus",
        "Pow",
        "Multiply",
        "Divide",
        "Subtract",
        "Negate",
        "Max",
        "Min",
        # Logic / conditional
        "If",
        "Greater",
        "Less",
        "GreaterEqual",
        "LessEqual",
        "Equal",
        "NotEqual",
        "And",
        "Or",
        "Not",
        # Misc
        "Clip",
        "Count",
        # Internal compiler constant wrapper (generated by Rust compiler)
        "Const",
    }
    # Subset of QLIB_OPERATORS that is ONLY supported by our Matrix Engine
    # (core/alphaeval/rq_eval.py). These operators are NOT registered in stock qlib,
    # so when --mode qlib is selected they must be removed from the prompt and
    # rejected by the validator (otherwise eval_agent silently falls back to
    # simulated metrics).
    _MATRIX_ENGINE_ONLY_OPS = frozenset({
        "CSRank", "CSZScore", "GroupNeutral", "Winsorize", "Percentile", "Scale",
    })

    # Verified Whitelist of supported data fields
    QLIB_FIELDS = {"$close", "$open", "$high", "$low", "$volume", "$vwap"}

    OPERATOR_SIGNATURES = """
Cross-sectional operators (applied across all stocks on a given day):
- Rank(df): Cross-sectional rank, returns value in (0, 1].
- CSRank(df): Same as Rank(df).
- CSZScore(df): Cross-sectional Z-score (mean=0, std=1).
- GroupNeutral(df): Subtract cross-sectional mean.
- Winsorize(df, pct): Clip outliers at pct and 1-pct quantiles (e.g., pct=0.05).
- Percentile(df): Cross-sectional percentile rank in (0, 1].
- Scale(df, a=1): Scale so that sum(abs(df)) == a across the cross-section.

Time-series operators (applied along the time axis per instrument):
- Mean(df, n): Rolling mean over n days.
- Std(df, n): Rolling standard deviation over n days.
- Med(df, n): Rolling median over n days. (Alias: Median)
- EMA(df, n): Exponential moving average with span=n.
- WMA(df, n): Weighted moving average with span=n.
- Sum(df, n): Rolling sum over n days.
- Ref(df, n): Value from n days AGO (n must be a positive integer; negative n means future data and is FORBIDDEN).
- Delta(df, n): df minus Ref(df, n), i.e., n-day change.
- Ts_Rank(df, n): Time-series percentile rank of current value over past n days.
- Ts_Max(df, n): Rolling max over n days.
- Ts_Min(df, n): Rolling min over n days.
- Ts_ArgMax(df, n): Days since the maximum in the past n days.
- Ts_ArgMin(df, n): Days since the minimum in the past n days.
- Ts_Percentile(df, n, p): p-th percentile value over n days (p in 0-100).

Correlation / covariance (time-series, per instrument):
- Corr(df1, df2, n): Rolling correlation over n days. df1 and df2 MUST be DIFFERENT expressions.
- Cov(df1, df2, n): Rolling covariance over n days. df1 and df2 MUST be DIFFERENT expressions.

Math unary:
- Abs(df): Absolute value.
- Log(df): Natural logarithm (df must be positive).
- Sign(df): -1, 0, or +1.
- Sqrt(df): Square root.
- Exp(df): Exponential e^df.
- Pow(df, n): df raised to the power n (e.g., Pow($close, 2)).
- Ceil(df), Floor(df): Ceiling / floor.
- Neg(df): Negate.
- Inv(df): 1 / df.

Math binary:
- Add(a, b), Sub(a, b), Mul(a, b), Div(a, b): Arithmetic.
- Max(a, b), Min(a, b): Element-wise max/min.

Logic / conditional:
- If(cond, a, b): Element-wise if-then-else.
- Greater(a, b), Less(a, b), GreaterEqual(a, b), LessEqual(a, b): Comparisons.
- And(a, b), Or(a, b), Not(a): Boolean operators.
- Clip(df, lower, upper): Clip values to [lower, upper].
"""

    def __init__(
        self,
        provider: str = None,
        model: str = None,
        base_url: str = None,
        reasoning_effort: str = None,
    ):
        self.llm = get_llm(
            temperature=0.1,
            provider=provider,
            model_name=model,
            base_url=base_url,
            reasoning_effort=reasoning_effort,
        )  # Lower temperature for strictness

# --- JSON Parsing & Sanitization ---

    @staticmethod
    def _strip_markdown_json(text: str) -> str:
        """Remove markdown code block wrapper and sanitize common JSON issues."""
        text = text.strip()
        # Remove markdown blocks (more robust with DOTALL)
        if "```json" in text:
            text = re.sub(r".*?```json\s*", "", text, flags=re.DOTALL)
            text = re.sub(r"\s*```.*", "", text, flags=re.DOTALL)
        elif "```" in text:
            text = re.sub(r".*?```\s*", "", text, flags=re.DOTALL)
            text = re.sub(r"\s*```.*", "", text, flags=re.DOTALL)

        # Remove potential preamble or postamble (look for first { and last })
        first_brace = text.find("{")
        last_brace = text.rfind("}")
        if first_brace != -1 and last_brace != -1:
            text = text[first_brace : last_brace + 1]

        # Strip strictly-illegal non-printables but PRESERVE \n \t \r — those are
        # common inside LaTeX formulas returned by the LLM and are tolerated by
        # json.loads(..., strict=False) downstream in _parse_llm_json().
        text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]", " ", text)

        return text.strip()

    @staticmethod
    def _parse_llm_json(text: str) -> dict:
        """Parse a JSON object emitted by an LLM, tolerant of common quirks.

        Pydantic's model_validate_json uses a strict RFC-8259 parser which
        rejects literal control characters (\\n, \\t, \\r) inside string
        values — but LLMs frequently emit multi-line LaTeX formulas like
        '\\\\begin{bmatrix}\\n...\\n\\\\end{bmatrix}' where the newlines are
        raw bytes, not escape sequences. Python's stdlib json supports
        strict=False which accepts those. We use that as the primary parser
        so downstream pydantic validation runs on a dict, bypassing the
        strict JSON path entirely.
        """
        cleaned = FactorAgent._strip_markdown_json(text)

        # First attempt: lenient parse (accepts literal control chars in strings)
        try:
            return json.loads(cleaned, strict=False)
        except (json.JSONDecodeError, ValueError):
            pass

        # Second attempt: fix stray single backslashes common in LaTeX
        # formulas (e.g. "\alpha" -> "\\alpha"). This must be string-aware:
        # a regex cannot reliably handle runs like "\\\rho" or escaped quotes.
        fixed = FactorAgent._escape_invalid_backslashes_in_strings(cleaned)
        try:
            return json.loads(fixed, strict=False)
        except (json.JSONDecodeError, ValueError) as e:
            # Last-resort: escape any remaining raw control chars inside string
            # values. This walks the text, tracks string context, and replaces
            # \n/\t/\r with their escaped forms only inside string literals.
            escaped = FactorAgent._escape_control_chars_in_strings(fixed)
            try:
                return json.loads(escaped, strict=False)
            except (json.JSONDecodeError, ValueError):
                raise ValueError(f"Unparseable LLM JSON response: {e}") from e

    @staticmethod
    def _short_error(exc: Exception, limit: int = 500) -> str:
        message = re.sub(r"\s+", " ", str(exc)).strip()
        if len(message) <= limit:
            return message
        return message[: limit - 3] + "..."

    @staticmethod
    def _escape_invalid_backslashes_in_strings(text: str) -> str:
        """Escape JSON-invalid backslashes inside string literals.

        LLMs often return LaTeX like ``\\max`` or ``\\rho`` in JSON strings.
        JSON only permits a small set of escapes, so those raw backslashes
        must become literal backslashes before json.loads can parse the object.
        """
        out = []
        in_string = False
        i = 0
        while i < len(text):
            ch = text[i]
            if ch == '"' and (i == 0 or text[i - 1] != "\\"):
                in_string = not in_string
                out.append(ch)
                i += 1
                continue
            if in_string and ch == "\\":
                next_ch = text[i + 1] if i + 1 < len(text) else ""
                if next_ch in {'"', "\\", "/"}:
                    out.append(ch)
                    out.append(next_ch)
                    i += 2
                    continue
                if next_ch == "u" and re.match(r"u[0-9a-fA-F]{4}", text[i + 1 : i + 6]):
                    out.append(text[i : i + 6])
                    i += 6
                    continue
                out.append("\\\\")
                i += 1
                continue
            out.append(ch)
            i += 1
        return "".join(out)

    @staticmethod
    def _escape_control_chars_in_strings(text: str) -> str:
        """Escape raw \\n/\\t/\\r inside JSON string literals. Tracks string
        context via an unescaped-quote counter."""
        out = []
        in_string = False
        i = 0
        while i < len(text):
            ch = text[i]
            if ch == '"' and (i == 0 or text[i - 1] != "\\"):
                in_string = not in_string
                out.append(ch)
            elif in_string and ch == "\n":
                out.append("\\n")
            elif in_string and ch == "\t":
                out.append("\\t")
            elif in_string and ch == "\r":
                out.append("\\r")
            else:
                out.append(ch)
            i += 1
        return "".join(out)

# --- Expression Validation & Repair ---

    def _validate_qlib_expression(self, expr: str, evaluation_mode: str = "ricequant") -> tuple:
        import ast

        if not expr or not expr.strip():
            return False, "Expression is empty."

        forbidden_ops = (
            self._MATRIX_ENGINE_ONLY_OPS if evaluation_mode == "qlib" else frozenset()
        )

        if "Cannot be expressed" in expr or "whitelist" in expr:
            return False, "LLM returned a refusal/explanation instead of a formula."

        # Check balanced parentheses
        depth = 0
        for ch in expr:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if depth < 0:
                return False, "Unbalanced parentheses: extra closing ')'."
        if depth != 0:
            return False, f"Unbalanced parentheses: {depth} unclosed '('."

        if "$" not in expr:
            return False, "Expression contains no Qlib field references (e.g., $close)."

        # Strict field validation: all $xxx must be in QLIB_FIELDS
        all_fields = re.findall(r"\$\w+", expr)
        for f in all_fields:
            if f not in self.QLIB_FIELDS:
                return (
                    False,
                    f"Field '{f}' is not in the supported whitelist: {list(self.QLIB_FIELDS)}.",
                )

        # Replace $field with dummy variable so ast can parse it
        safe_expr = re.sub(r"\$(\w+)", r"field_\1", expr)

        try:
            tree = ast.parse(safe_expr, mode="eval")
        except SyntaxError as e:
            return False, f"Syntax Error: {e.msg}"

        container_nodes = (ast.Tuple, ast.List, ast.Dict, ast.Set)
        if isinstance(tree.body, container_nodes):
            return (
                False,
                "Expression must evaluate to one factor series, not a Python container/tuple.",
            )
        for node in ast.walk(tree):
            if isinstance(node, container_nodes):
                return (
                    False,
                    "Expression contains a Python container/tuple; return a single factor expression.",
                )

        binary_ops = {
            "Mean",
            "Std",
            "Med",
            "Median",
            "EMA",
            "WMA",
            "Ref",
            "Sum",
            "Delta",
            "Ts_Rank",
            "Ts_Max",
            "Ts_Min",
            "Ts_ArgMax",
            "Ts_ArgMin",
            "Add",
            "Sub",
            "Mul",
            "Div",
            "Mult",
            "Divi",
            "Plus",
            "Minus",
            "Multiply",
            "Divide",
            "Subtract",
            "Pow",
            "Greater",
            "Less",
            "GreaterEqual",
            "LessEqual",
            "Equal",
            "NotEqual",
            "And",
            "Or",
            "Max",
            "Min",
            "Count",
        }
        ternary_ops = {"Corr", "Correlation", "Cov", "Ts_Percentile", "If", "Clip"}
        # Operators that accept exactly 1 data argument (plus optional scalars)
        unary_ops = {
            "Rank", "CSRank", "CSZScore", "GroupNeutral", "Winsorize",
            "Percentile", "Scale", "Abs", "Log", "Sign", "Sqrt", "Exp",
            "Neg", "Negate", "Inv", "Not", "Ceil", "Floor",
        }

        # qlib mode: Rank is a time-series rolling operator that requires N
        if evaluation_mode == "qlib":
            binary_ops.add("Rank")
            unary_ops.discard("Rank")

        exact_one_arg_ops = {
            "CSZScore", "GroupNeutral", "Percentile", "Abs", "Log", "Sign",
            "Sqrt", "Exp", "Neg", "Negate", "Inv", "Not", "Ceil", "Floor",
        }
        rolling_window_ops = {
            "Mean", "Std", "Med", "Median", "EMA", "WMA", "Ref", "Sum",
            "Delta", "Ts_Rank", "Ts_Max", "Ts_Min", "Ts_ArgMax",
            "Ts_ArgMin", "Count",
        }

        def constant_number(node: ast.AST):
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                return node.value
            if (
                isinstance(node, ast.UnaryOp)
                and isinstance(node.op, ast.USub)
                and isinstance(node.operand, ast.Constant)
                and isinstance(node.operand.value, (int, float))
            ):
                return -node.operand.value
            return None

        def is_integer_window(node: ast.AST, *, allow_zero: bool = False) -> bool:
            value = constant_number(node)
            if value is None or int(value) != value:
                return False
            return value >= 0 if allow_zero else value > 0

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    op = node.func.id
                    if op not in self.QLIB_OPERATORS and op not in {
                        "fields",
                        "np",
                        "pd",
                    }:
                        return (
                            False,
                            f"Operator '{op}' is not in the supported whitelist.",
                        )

                    if op in forbidden_ops:
                        return (
                            False,
                            f"Operator '{op}' is NOT supported by the qlib backend "
                            f"(only available with --mode ricequant). "
                            f"Compose an equivalent expression using qlib-native operators "
                            f"(Mean, Std, Sum, Rank, Ts_Rank, Ts_Max, Ts_Min, etc.).",
                        )

                    arg_count = len(node.args) + len(node.keywords)
                    if op in unary_ops and arg_count < 1:
                        return (
                            False,
                            f"Operator '{op}' requires at least 1 argument, but got {arg_count}.",
                        )
                    # Rank/CSRank only take 1 data arg — extra positional args are invalid
                    # (qlib mode: Rank is time-series and REQUIRES N; check below)
                    if (
                        op in {"CSRank"}
                        or (op == "Rank" and evaluation_mode != "qlib")
                    ) and len(node.args) > 1:
                        return (
                            False,
                            f"Operator '{op}' takes exactly 1 argument, but got {len(node.args)}. "
                            "Do NOT pass a window size to Rank() — it is always cross-sectional.",
                        )
                    if op in binary_ops and arg_count < 2:
                        return (
                            False,
                            f"Operator '{op}' requires at least 2 arguments, but got {arg_count}.",
                        )
                    exact_two_arg_ops = {
                        "Add",
                        "Sub",
                        "Mul",
                        "Div",
                        "Mult",
                        "Divi",
                        "Plus",
                        "Minus",
                        "Multiply",
                        "Divide",
                        "Subtract",
                        "Pow",
                        "Greater",
                        "Less",
                        "GreaterEqual",
                        "LessEqual",
                        "Equal",
                        "NotEqual",
                        "Max",
                        "Min",
                    }
                    if op in exact_two_arg_ops and (len(node.args) != 2 or node.keywords):
                        return (
                            False,
                            f"Operator '{op}' takes exactly 2 positional arguments, but got {arg_count}.",
                        )
                    if op in ternary_ops and arg_count < 3:
                        return (
                            False,
                            f"Operator '{op}' requires 3 arguments, but got {arg_count}.",
                        )
                    if op in exact_one_arg_ops and arg_count != 1:
                        return (
                            False,
                            f"Operator '{op}' takes exactly 1 argument, but got {arg_count}.",
                        )
                    if op in rolling_window_ops:
                        if len(node.args) != 2 or node.keywords:
                            return (
                                False,
                                f"Operator '{op}' takes exactly 2 positional arguments: data and integer window.",
                            )
                        if not is_integer_window(node.args[1]):
                            return (
                                False,
                                f"Operator '{op}' window must be a positive constant integer.",
                            )
                    if op == "Rank" and evaluation_mode == "qlib":
                        if len(node.args) != 2 or node.keywords:
                            return (
                                False,
                                "Operator 'Rank' takes exactly 2 positional arguments in qlib mode: data and integer window.",
                            )
                        if not is_integer_window(node.args[1], allow_zero=True):
                            return (
                                False,
                                "Operator 'Rank' window must be a non-negative constant integer in qlib mode.",
                            )
                    if op in {"Corr", "Correlation", "Cov"}:
                        if len(node.args) != 3 or node.keywords:
                            return (
                                False,
                                f"Operator '{op}' takes exactly 3 positional arguments: data1, data2, integer window.",
                            )
                        if not is_integer_window(node.args[2]):
                            return (
                                False,
                                f"Operator '{op}' window must be a positive constant integer.",
                            )
                    if op == "Ts_Percentile":
                        if len(node.args) != 3 or node.keywords:
                            return (
                                False,
                                "Operator 'Ts_Percentile' takes exactly 3 positional arguments: data, integer window, percentile.",
                            )
                        if not is_integer_window(node.args[1]):
                            return (
                                False,
                                "Operator 'Ts_Percentile' window must be a positive constant integer.",
                            )
                        p_value = constant_number(node.args[2])
                        if p_value is None:
                            return (
                                False,
                                "Operator 'Ts_Percentile' percentile must be a constant number.",
                            )

                    # Tautology check: Div/Sub with identical operands → constant factor
                    if op in {"Div", "Divi", "Divide", "Sub", "Subtract", "Minus"} and len(node.args) >= 2:
                        if ast.dump(node.args[0]) == ast.dump(node.args[1]):
                            return (
                                False,
                                f"'{op}' has identical first and second arguments — this always produces a constant (1.0 or 0.0) with zero cross-sectional variance. Use two DIFFERENT expressions.",
                            )

                    # Self-correlation check: Corr(a, a, n) or Cov(a, a, n)
                    if op in {"Corr", "Correlation", "Cov"} and len(node.args) >= 2:
                        if ast.dump(node.args[0]) == ast.dump(node.args[1]):
                            return (
                                False,
                                f"'{op}' has identical first and second arguments — this is always 1.0 and meaningless. Use two DIFFERENT expressions.",
                            )

                    # Look-ahead check: Ref(x, n) with negative n
                    if op == "Ref" and len(node.args) >= 2:
                        n_arg = node.args[1]
                        n_val = None
                        if isinstance(n_arg, ast.Constant):
                            n_val = n_arg.value
                        elif isinstance(n_arg, ast.UnaryOp) and isinstance(n_arg.op, ast.USub):
                            if isinstance(n_arg.operand, ast.Constant):
                                n_val = -n_arg.operand.value
                        if n_val is not None and n_val < 0:
                            return (
                                False,
                                f"Ref(x, {n_val}) uses a negative offset which means FUTURE data — this is look-ahead bias and is forbidden. Use positive n for past data.",
                            )
                else:
                    return False, "Complex function calls are not supported."

        return True, "OK"

    @staticmethod
    def _repair_unclosed_parentheses(expr: str) -> str:
        """Append missing trailing ')' only when there are no extra closers."""
        text = (expr or "").strip()
        depth = 0
        for ch in text:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if depth < 0:
                return text
        if depth > 0:
            return text + (")" * depth)
        return text

    @staticmethod
    def _repair_trailing_extra_parentheses(expr: str) -> str:
        """Remove redundant trailing ')' only when that fully balances the expression."""
        text = (expr or "").strip()
        if not text or not text.endswith(")"):
            return text

        def balance(candidate: str) -> tuple[bool, bool]:
            depth = 0
            saw_extra = False
            for ch in candidate:
                if ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
                if depth < 0:
                    saw_extra = True
                    break
            return saw_extra, depth == 0

        saw_extra, balanced = balance(text)
        if not saw_extra and balanced:
            return text

        candidate = text
        while candidate.endswith(")"):
            candidate = candidate[:-1].rstrip()
            candidate_saw_extra, candidate_balanced = balance(candidate)
            if not candidate_saw_extra and candidate_balanced:
                return candidate

        return text

    @classmethod
    def _repair_parentheses(cls, expr: str) -> str:
        text = cls._repair_unclosed_parentheses(expr)
        return cls._repair_trailing_extra_parentheses(text)

    @staticmethod
    def _repair_common_arity_issues(expr: str, evaluation_mode: str = "ricequant") -> str:
        """Normalize common LLM arity mistakes before strict validation."""
        import ast

        text = (expr or "").strip()
        if not text:
            return text

        field_names: dict[str, str] = {}

        def field_repl(match: re.Match[str]) -> str:
            name = f"field_{match.group(1)}"
            field_names[name] = match.group(0)
            return name

        safe_expr = re.sub(r"\$(\w+)", field_repl, text)

        try:
            tree = ast.parse(safe_expr, mode="eval")
        except SyntaxError:
            return text

        changed = False

        def constant_number(node: ast.AST):
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                return node.value
            if (
                isinstance(node, ast.UnaryOp)
                and isinstance(node.op, ast.USub)
                and isinstance(node.operand, ast.Constant)
                and isinstance(node.operand.value, (int, float))
            ):
                return -node.operand.value
            return None

        def is_integer_window(node: ast.AST, *, allow_zero: bool = False) -> bool:
            value = constant_number(node)
            if value is None or int(value) != value:
                return False
            return value >= 0 if allow_zero else value > 0

        default_window_by_op = {
            "Ref": 1,
            "Delta": 1,
            "Mean": 20,
            "Std": 20,
            "Median": 20,
            "EMA": 20,
            "WMA": 20,
            "Sum": 20,
            "Ts_Rank": 20,
            "Ts_Max": 20,
            "Ts_Min": 20,
            "Ts_ArgMax": 20,
            "Ts_ArgMin": 20,
            "Count": 20,
        }

        class ArityRepair(ast.NodeTransformer):
            def visit_Call(self, node: ast.Call):  # type: ignore[override]
                nonlocal changed
                node = self.generic_visit(node)
                if not isinstance(node.func, ast.Name):
                    return node

                op = node.func.id
                if not node.keywords and op == "Med":
                    changed = True
                    op = "Median"
                    node.func.id = op

                if not node.keywords and op == "If" and len(node.args) in {1, 2}:
                    changed = True
                    fallback = ast.Constant(value=0)
                    if len(node.args) == 1:
                        node.args = [node.args[0], ast.Constant(value=1), fallback]
                    else:
                        node.args = [node.args[0], node.args[1], fallback]
                    return node

                if not node.keywords and op in {"Sub", "Subtract", "Minus"} and len(node.args) == 1:
                    changed = True
                    return ast.copy_location(
                        ast.Call(func=ast.Name(id="Neg", ctx=ast.Load()), args=node.args, keywords=[]),
                        node,
                    )

                if (
                    not node.keywords
                    and op in {"Add", "Plus", "Mul", "Mult", "Multiply"}
                    and len(node.args) == 1
                ):
                    changed = True
                    return node.args[0]

                if (
                    not node.keywords
                    and op in {
                        "Add",
                        "Plus",
                        "Mul",
                        "Mult",
                        "Multiply",
                        "Sub",
                        "Subtract",
                        "Minus",
                        "Div",
                        "Divi",
                        "Divide",
                        "Pow",
                        "Max",
                        "Min",
                    }
                    and len(node.args) > 2
                ):
                    changed = True
                    folded = ast.Call(
                        func=ast.Name(id=op, ctx=ast.Load()),
                        args=[node.args[0], node.args[1]],
                        keywords=[],
                    )
                    for extra_arg in node.args[2:]:
                        folded = ast.Call(
                            func=ast.Name(id=op, ctx=ast.Load()),
                            args=[folded, extra_arg],
                            keywords=[],
                        )
                    return ast.copy_location(folded, node)

                if not node.keywords and len(node.args) == 1:
                    default_window = default_window_by_op.get(op)
                    if default_window is not None:
                        changed = True
                        node.args.append(ast.Constant(value=default_window))
                        return node

                if (
                    not node.keywords
                    and len(node.args) == 2
                    and op in default_window_by_op
                    and not is_integer_window(node.args[1])
                ):
                    changed = True
                    node.args[1] = ast.Constant(value=default_window_by_op[op])
                    return node

                if not node.keywords and op in {"Corr", "Correlation", "Cov"} and len(node.args) == 2:
                    changed = True
                    node.args.append(ast.Constant(value=20))
                    return node

                if (
                    not node.keywords
                    and op in {"Corr", "Correlation", "Cov"}
                    and len(node.args) == 3
                    and not is_integer_window(node.args[2])
                ):
                    changed = True
                    node.args[2] = ast.Constant(value=20)
                    return node

                if (
                    not node.keywords
                    and op == "Ts_Percentile"
                    and len(node.args) == 3
                ):
                    if not is_integer_window(node.args[1]):
                        changed = True
                        node.args[1] = ast.Constant(value=20)
                    if constant_number(node.args[2]) is None:
                        changed = True
                        node.args[2] = ast.Constant(value=50)
                    return node

                if (
                    evaluation_mode == "qlib"
                    and not node.keywords
                    and op == "Rank"
                    and len(node.args) == 2
                    and not is_integer_window(node.args[1], allow_zero=True)
                ):
                    changed = True
                    node.args[1] = ast.Constant(value=20)
                    return node

                if (
                    evaluation_mode != "qlib"
                    and not node.keywords
                    and op in {"Rank", "CSRank", "CSZScore", "GroupNeutral", "Percentile"}
                    and len(node.args) > 1
                ):
                    changed = True
                    node.args = node.args[:1]

                return node

        repaired_tree = ArityRepair().visit(tree)
        if not changed:
            return text

        ast.fix_missing_locations(repaired_tree)
        repaired = ast.unparse(repaired_tree)
        for safe_name, original in sorted(field_names.items(), key=lambda item: len(item[0]), reverse=True):
            repaired = re.sub(rf"\b{re.escape(safe_name)}\b", original, repaired)
        return repaired

# --- FactorAgent Entry Point (__call__) ---

    def __call__(self, state: AlphaMinerState) -> Dict[str, Any]:
        hypothesis_desc = state.get("hypothesis_description", "")
        rationale = state.get("rationale", "")
        evaluation_mode = (state.get("evaluation_mode") or "ricequant").lower()

        logger.info("[FactorAgent] Starting formalization and implementation")

        if not hypothesis_desc:
            return {
                "error": "No hypothesis found in state.",
                "messages": ["[FactorAgent] Error: Missing hypothesis."],
            }

        # 1. Convert text to math language (Single pass)
        try:
            form_prompt = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        "You are a quantitative researcher expert in mathematics and statistics. "
                        "Convert the given financial hypothesis into a strict mathematical formula. "
                        "Clearly define each variable. "
                        "You MUST respond with valid JSON only, no markdown, no explanations.\n"
                        "CRITICAL: If the formula contains backslashes (e.g., LaTeX), you MUST double-escape them in the JSON string (e.g., \\\\alpha).",
                    ),
                    (
                        "user",
                        "Hypothesis: {hypothesis}\nRationale: {rationale}\n\n"
                        "Return ONLY valid JSON matching this exact schema:\n"
                        '{{"math_formula": "string", "variables_defined": {{"var": "definition"}}}}\n\n'
                        "Ensure ALL math symbols and formulas are correctly escaped for JSON compatibility.",
                    ),
                ]
            )
            form_chain = form_prompt | self.llm
            form_result = None
            form_error = ""
            max_form_retries = 2
            for form_retry in range(max_form_retries + 1):
                if form_retry > 0:
                    logger.warning(
                        f"[FactorAgent] Retrying formalization JSON parse "
                        f"({form_retry}/{max_form_retries}): {form_error}"
                    )
                logger.info("[FactorAgent] LLM is formalizing the hypothesis into math...")
                raw_form_response = form_chain.invoke(
                    {"hypothesis": hypothesis_desc, "rationale": rationale}
                )
                try:
                    form_dict = self._parse_llm_json(raw_form_response.content)
                    form_result = FormalizationOutput.model_validate(form_dict)
                    break
                except (ValueError, ValidationError) as e:
                    form_error = (
                        "Formalization JSON parse/validation failed: "
                        f"{self._short_error(e)}"
                    )

            if form_result is None:
                logger.error(f"[FactorAgent] {form_error}")
                return {
                    "math_formula": "",
                    "variables_defined": {},
                    "code_expression": "Const(0)",
                    "is_valid_syntax": False,
                    "syntax_error": form_error,
                    "messages": [f"[FactorAgent] Error: {form_error}"],
                }

            logger.info(f"[FactorAgent] Formalized Math: {form_result.math_formula}")

            # 2. Implementation with Self-Correction Retry Loop
            max_retries = 2
            current_retry = 0
            code_expression = ""
            is_valid_syntax = False
            error_feedback = ""

            if evaluation_mode == "qlib":
                backend_restriction = (
                    "\n### BACKEND-SPECIFIC RESTRICTIONS (current backend = qlib):\n"
                    "The following operators are listed above for completeness but are "
                    "NOT registered in stock qlib and WILL be rejected by the validator: "
                    f"{', '.join(sorted(self._MATRIX_ENGINE_ONLY_OPS))}.\n"
                    "IMPORTANT — qlib mode changes:\n"
                    "  - Rank(feature, N) is a TIME-SERIES rolling rank over N days "
                    "(NOT cross-sectional). N is REQUIRED. Use N=0 for expanding-window rank.\n"
                    "  - Ts_Rank(feature, N) is identical to Rank(feature, N) in qlib mode.\n"
                    "  - Avoid GroupNeutral / Winsorize / Percentile / Scale entirely; "
                    "compose equivalents from Mean/Std/Sub/Div/Clip if needed.\n"
                )
            else:
                backend_restriction = ""

            # Seed the conversation for implementation
            messages = [
                (
                    "system",
                    "You are an expert Qlib developer. Convert the following mathematical formula into a syntactically correct Qlib Alpha158 expression.\n\n"
                    "### SUPPORTED OPERATORS & SIGNATURES:\n"
                    f"{self.OPERATOR_SIGNATURES}\n"
                    + (
                        "**QLIB-MODE CORRECTIONS to the signatures above:**\n"
                        "- Rank(feature, N) is a TIME-SERIES rolling rank over N days (REQUIRES N). N=0 → expanding-window rank.\n"
                        "- Max(feature, N) and Min(feature, N) are ROLLING max/min over N days (NOT element-wise binary).\n"
                        "- Ts_Max/Ts_Min are aliases for Max/Min.\n"
                        "- CSRank, CSZScore, GroupNeutral, Winsorize, Percentile, Scale: NOT available in qlib mode.\n\n"
                        if evaluation_mode == "qlib"
                        else ""
                    )
                    + f"{backend_restriction}\n"
                    + "### ALLOWED DATA FIELDS (STRICT WHITELIST):\n"
                    + f"ONLY these fields exist: {', '.join(sorted(list(self.QLIB_FIELDS)))}.\n"
                    + "DO NOT use any other fields such as $beta_spx, $market_cap, $pe_ratio, $factor, $sector, $index, etc.\n"
                    + "If your formula references a field not in the whitelist, replace it with an approximation using the allowed fields.\n\n"
                    + "### MANDATORY RULES:\n"
                    + "1. ONLY use the operators listed above. Do not assume any other operator exists.\n"
                    + "2. Use $field for data fields. **STRICTLY PROHIBITED**: $PPI, $CPI, $swap, $dividend, $beta, $cap, $cash, $debt, or any other field not in the whitelist.\n"
                    + "3. Window parameters (n, d, window_size) MUST be constant integers (e.g., 5, 10, 20). **NEVER** use a dynamic expression or field as a window size.\n"
                    + "4. If a logic requires an unlisted operator, simplify it using ONLY the allowed ones.\n"
                    + "5. AVOID hollow logic like $close/$close or Sign(1). The resulting factor must have meaningful cross-sectional variance.\n"
                    + "6. You MUST respond with valid JSON only, no markdown, no explanations.\n"
                    + "7. Ensure all characters are correctly escaped for JSON compatibility.\n"
                    + "8. AVOID pure binary signals (e.g., If(cond, 1, 0)). Prefer continuous expressions that vary smoothly across all stocks.\n"
                    + "9. ABSOLUTELY FORBIDDEN — LOOK-AHEAD BIAS: Ref(x, n) with n < 0 means FUTURE data and is strictly forbidden. Only use Ref(x, n) with positive n (past data).\n"
                    + "10. ABSOLUTELY FORBIDDEN — SELF-CORRELATION: Never use Corr(a, a, n) or Cov(a, a, n) where both arguments are the same expression (result is always trivially 1.0). The two series in Corr/Cov MUST be meaningfully different.\n"
                    + "11. ABSOLUTELY FORBIDDEN — TAUTOLOGICAL FACTORS: Never write Div(x, x), Sub(x, x), or any expression where both operands are identical (result is always 1.0 or 0.0 with zero cross-sectional variance). The numerator and denominator of any division MUST be different.\n"
                    + (
                        "12. Rank(feature, N) takes EXACTLY 2 arguments — "
                        "the data series AND the rolling window size N in days. "
                        "Use N=0 for expanding-window rank. "
                        "CSRank is FORBIDDEN in this backend."
                        if evaluation_mode == "qlib"
                        else "12. Rank() and CSRank() take EXACTLY 1 argument — "
                        "the data series. Do NOT pass a window size as a second argument."
                    ),
                ),
                (
                    "user",
                    "Mathematical Formula: {math_formula}\nVariables: {variables}\n\n"
                    "Return ONLY valid JSON matching this exact schema:\n"
                    '{{"code_expression": "string", "is_valid_syntax": boolean}}\n\n'
                    "Ensure the JSON is correctly formatted and escaped.",
                ),
            ]

            while current_retry <= max_retries:
                if current_retry > 0:
                    logger.warning(
                        f"[FactorAgent] Retry {current_retry}/{max_retries} due to syntax error: {error_feedback}"
                    )
                    # Sliding window: only keep the base 2 messages + last retry pair to avoid
                    # unbounded token growth and prevent LangChain template variable misinterpretation.
                    # Escape any literal braces in dynamic values so LangChain's PromptTemplate
                    # does not try to interpolate them as template variables.
                    safe_code = code_expression.replace("{", "{{").replace("}", "}}")
                    safe_feedback = error_feedback.replace("{", "{{").replace("}", "}}")
                    messages = messages[:2] + [
                        (
                            "assistant",
                            f'{{{{ "code_expression": "{safe_code}", "is_valid_syntax": false }}}}',
                        ),
                        (
                            "user",
                            f"The previous response failed validation: {safe_feedback}. Please FIX IT and return only the valid JSON.",
                        ),
                    ]

                impl_prompt = ChatPromptTemplate.from_messages(messages)
                impl_chain = impl_prompt | self.llm

                logger.info(
                    f"[FactorAgent] LLM is generating Qlib code (Retry {current_retry})..."
                )
                raw_impl_response = impl_chain.invoke(
                    {
                        "math_formula": form_result.math_formula,
                        "variables": str(form_result.variables_defined),
                    }
                )

                try:
                    impl_dict = self._parse_llm_json(raw_impl_response.content)
                    impl_result = ImplementationOutput.model_validate(impl_dict)
                except (ValueError, ValidationError) as e:
                    error_feedback = (
                        "Implementation JSON parse/validation failed: "
                        f"{self._short_error(e)}"
                    )
                    logger.warning(f"[FactorAgent] {error_feedback}")
                    current_retry += 1
                    continue

                raw_code_expression = impl_result.code_expression
                code_expression = self._repair_parentheses(raw_code_expression)
                if code_expression != raw_code_expression:
                    logger.warning(
                        "[FactorAgent] Auto-repaired expression parentheses before validation."
                    )
                arity_repaired_expression = self._repair_common_arity_issues(
                    code_expression, evaluation_mode=evaluation_mode
                )
                if arity_repaired_expression != code_expression:
                    logger.warning(
                        "[FactorAgent] Auto-repaired common operator arity issue before validation."
                    )
                    code_expression = arity_repaired_expression

                # Independent validation
                is_valid, validation_msg = self._validate_qlib_expression(
                    code_expression, evaluation_mode=evaluation_mode
                )

                if is_valid:
                    # Secondary validation: Mock execution (Dry Run)
                    try:
                        from aiminer.core.alphaeval.rq_eval import RiceQuantEval

                        is_mock_ok, mock_msg = RiceQuantEval.dry_run(code_expression)
                        if not is_mock_ok:
                            is_valid = False
                            validation_msg = (
                                f"Runtime Error during Mock Execution: {mock_msg}"
                            )
                    except Exception as dry_e:
                        logger.warning(f"Dry run could not be performed: {dry_e}")

                if is_valid:
                    is_valid_syntax = True
                    logger.info(
                        f"[FactorAgent] Implemented Code (Success): {code_expression}"
                    )
                    break
                else:
                    error_feedback = validation_msg
                    current_retry += 1

            if not is_valid_syntax:
                logger.error(
                    f"[FactorAgent] Failed to fix syntax after {max_retries} retries."
                )
                if not code_expression:
                    code_expression = "Const(0)"

            return {
                "math_formula": form_result.math_formula,
                "variables_defined": form_result.variables_defined,
                "code_expression": code_expression,
                "is_valid_syntax": is_valid_syntax,
                "syntax_error": None if is_valid_syntax else error_feedback,
                "messages": [
                    f"[FactorAgent] Math: {form_result.math_formula}",
                    f"[FactorAgent] Code: {code_expression}",
                    f"[FactorAgent] Final Valid: {is_valid_syntax}",
                ],
            }

        except Exception as e:
            logger.error(f"[FactorAgent] Failed to process factor: {e}")
            return {"error": str(e), "messages": [f"[FactorAgent] Error: {e}"]}
