from __future__ import annotations
from typing import Dict, Any
from langchain_core.prompts import ChatPromptTemplate
import json
import re
from loguru import logger
from workflow.state import AlphaMinerState
from core.llm import get_llm
from schemas.messages import FormalizationOutput, ImplementationOutput


class FactorAgent:
    """
    FactorAgent translates the market hypothesis into executable code (Formalization and Implementation).
    """

    # Verified Whitelist of supported Qlib operators in our Matrix Engine (rq_eval.py)
    QLIB_OPERATORS = {
        # Cross-sectional
        "Rank",
        "CSRank",
        "CSZScore",
        "GroupNeutral",
        "Winsorize",
        "Percentile",
        # Time-series
        "Mean",
        "Std",
        "Median",
        "EMA",
        "Sum",
        "Ref",
        "Delta",
        "EMA",
        "Ts_Rank",
        "Ts_Max",
        "Ts_Min",
        "Ts_ArgMax",
        "Ts_ArgMin",
        "Ts_Percentile",
        # Correlation / covariance
        "Corr",
        "Correlation",
        "Cov",
        # Math unary
        "Abs",
        "Log",
        "Sign",
        "Sqrt",
        "Exp",
        "Neg",
        "Inv",
        "Ceil",
        "Floor",
        # Math binary / aliases
        "Add",
        "Sub",
        "Mul",
        "Div",
        "Mult",
        "Divi",
        "Plus",
        "Minus",
        "Pow",
        "Multiply",
        "Divide",
        "Subtract",
        "Negate",
        "Max",
        "Min",
        # Logic / conditional
        "If",
        "Greater",
        "Less",
        "GreaterEqual",
        "LessEqual",
        "Equal",
        "NotEqual",
        "And",
        "Or",
        "Not",
        # Misc
        "Clip",
        "Count",
        # Internal compiler constant wrapper (generated by Rust compiler)
        "Const",
    }
    # Verified Whitelist of supported data fields
    QLIB_FIELDS = {"$close", "$open", "$high", "$low", "$volume", "$vwap"}

    OPERATOR_SIGNATURES = """
- Rank(df): Cross-sectional rank (pct).
- CSRank(df): Same as Rank(df).
- CSZScore(df): Cross-sectional Z-score.
- Mean(df, n): Rolling mean over n days.
- Std(df, n): Rolling standard deviation over n days.
- Median(df, n): Rolling median over n days.
- EMA(df, n): Exponential moving average over n days.
- Abs(df): Absolute value.
- Ref(df, n): Value from n days ago.
- Log(df): Natural logarithm.
- Sum(df, n): Rolling sum over n days.
- If(cond, a, b): element-wise if-then-else.
- Greater(a, b), Less(a, b), And(a, b), Or(a, b): Logical operators.
- Delta(df, n): df - Ref(df, n).
- Corr(df1, df2, n): Rolling correlation over n days.
- Cov(df1, df2, n): Rolling covariance over n days.
- Ts_Rank(df, n): Time-series rank (pct) of current value over n days.
- Ts_Percentile(df, n, p): The value at the p-th percentile over n days (p defaults to 50).
- Ts_ArgMax(df, n), Ts_ArgMin(df, n): Days since max/min in n days.
- Winsorize(df, pct): Cross-sectional winsorization.
- GroupNeutral(df): Cross-sectional de-meaning.
- Sign(df), Sqrt(df): Math functions.
"""

    def __init__(self, provider: str = None, model: str = None):
        self.llm = get_llm(
            temperature=0.1, provider=provider, model_name=model
        )  # Lower temperature for strictness

    @staticmethod
    def _strip_markdown_json(text: str) -> str:
        """Remove markdown code block wrapper and sanitize common JSON issues."""
        text = text.strip()
        # Remove markdown blocks (more robust with DOTALL)
        if "```json" in text:
            text = re.sub(r".*?```json\s*", "", text, flags=re.DOTALL)
            text = re.sub(r"\s*```.*", "", text, flags=re.DOTALL)
        elif "```" in text:
            text = re.sub(r".*?```\s*", "", text, flags=re.DOTALL)
            text = re.sub(r"\s*```.*", "", text, flags=re.DOTALL)

        # Remove potential preamble or postamble (look for first { and last })
        first_brace = text.find("{")
        last_brace = text.rfind("}")
        if first_brace != -1 and last_brace != -1:
            text = text[first_brace : last_brace + 1]

        # Strip strictly-illegal non-printables but PRESERVE \n \t \r — those are
        # common inside LaTeX formulas returned by the LLM and are tolerated by
        # json.loads(..., strict=False) downstream in _parse_llm_json().
        text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]", " ", text)

        return text.strip()

    @staticmethod
    def _parse_llm_json(text: str) -> dict:
        """Parse a JSON object emitted by an LLM, tolerant of common quirks.

        Pydantic's model_validate_json uses a strict RFC-8259 parser which
        rejects literal control characters (\\n, \\t, \\r) inside string
        values — but LLMs frequently emit multi-line LaTeX formulas like
        '\\\\begin{bmatrix}\\n...\\n\\\\end{bmatrix}' where the newlines are
        raw bytes, not escape sequences. Python's stdlib json supports
        strict=False which accepts those. We use that as the primary parser
        so downstream pydantic validation runs on a dict, bypassing the
        strict JSON path entirely.
        """
        cleaned = FactorAgent._strip_markdown_json(text)

        # First attempt: lenient parse (accepts literal control chars in strings)
        try:
            return json.loads(cleaned, strict=False)
        except (json.JSONDecodeError, ValueError):
            pass

        # Second attempt: fix stray single backslashes common in LaTeX
        # formulas (e.g. "\alpha" → "\\alpha"). The negative lookbehind avoids
        # double-escaping already-escaped backslashes, and we intentionally do
        # NOT exclude [bfnrt] so LaTeX commands like \text, \frac, \begin get
        # escaped (in a math formula, \t is never a JSON tab escape).
        fixed = re.sub(r'(?<!\\)\\(?!(?:["\\/]|u[0-9a-fA-F]{4}))', r"\\\\", cleaned)
        try:
            return json.loads(fixed, strict=False)
        except (json.JSONDecodeError, ValueError) as e:
            # Last-resort: escape any remaining raw control chars inside string
            # values. This walks the text, tracks string context, and replaces
            # \n/\t/\r with their escaped forms only inside string literals.
            escaped = FactorAgent._escape_control_chars_in_strings(fixed)
            try:
                return json.loads(escaped, strict=False)
            except (json.JSONDecodeError, ValueError):
                raise ValueError(f"Unparseable LLM JSON response: {e}") from e

    @staticmethod
    def _escape_control_chars_in_strings(text: str) -> str:
        """Escape raw \\n/\\t/\\r inside JSON string literals. Tracks string
        context via an unescaped-quote counter."""
        out = []
        in_string = False
        i = 0
        while i < len(text):
            ch = text[i]
            if ch == '"' and (i == 0 or text[i - 1] != "\\"):
                in_string = not in_string
                out.append(ch)
            elif in_string and ch == "\n":
                out.append("\\n")
            elif in_string and ch == "\t":
                out.append("\\t")
            elif in_string and ch == "\r":
                out.append("\\r")
            else:
                out.append(ch)
            i += 1
        return "".join(out)

    def _validate_qlib_expression(self, expr: str) -> tuple:
        import ast

        if not expr or not expr.strip():
            return False, "Expression is empty."

        if "Cannot be expressed" in expr or "whitelist" in expr:
            return False, "LLM returned a refusal/explanation instead of a formula."

        # Check balanced parentheses
        depth = 0
        for ch in expr:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if depth < 0:
                return False, "Unbalanced parentheses: extra closing ')'."
        if depth != 0:
            return False, f"Unbalanced parentheses: {depth} unclosed '('."

        if "$" not in expr:
            return False, "Expression contains no Qlib field references (e.g., $close)."

        # Strict field validation: all $xxx must be in QLIB_FIELDS
        all_fields = re.findall(r"\$\w+", expr)
        for f in all_fields:
            if f not in self.QLIB_FIELDS:
                return (
                    False,
                    f"Field '{f}' is not in the supported whitelist: {list(self.QLIB_FIELDS)}.",
                )

        # Replace $field with dummy variable so ast can parse it
        safe_expr = re.sub(r"\$(\w+)", r"field_\1", expr)

        try:
            tree = ast.parse(safe_expr, mode="eval")
        except SyntaxError as e:
            return False, f"Syntax Error: {e.msg}"

        binary_ops = {
            "Mean",
            "Std",
            "Median",
            "EMA",
            "Ref",
            "Sum",
            "Delta",
            "Ts_Rank",
            "Ts_Max",
            "Ts_Min",
            "Ts_ArgMax",
            "Ts_ArgMin",
            "Add",
            "Sub",
            "Mul",
            "Div",
            "Mult",
            "Divi",
            "Plus",
            "Minus",
            "Pow",
            "Greater",
            "Less",
        }
        ternary_ops = {"Corr", "Correlation", "Cov", "Ts_Percentile", "If"}

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    op = node.func.id
                    if op not in self.QLIB_OPERATORS and op not in {
                        "fields",
                        "np",
                        "pd",
                    }:
                        return (
                            False,
                            f"Operator '{op}' is not in the supported whitelist.",
                        )

                    arg_count = len(node.args) + len(node.keywords)
                    if op in binary_ops and arg_count < 2:
                        return (
                            False,
                            f"Operator '{op}' requires at least 2 arguments, but got {arg_count}.",
                        )
                    if op in ternary_ops and arg_count < 3:
                        return (
                            False,
                            f"Operator '{op}' requires 3 arguments, but got {arg_count}.",
                        )
                else:
                    return False, "Complex function calls are not supported."

        return True, "OK"

    def __call__(self, state: AlphaMinerState) -> Dict[str, Any]:
        hypothesis_desc = state.get("hypothesis_description", "")
        rationale = state.get("rationale", "")

        logger.info("[FactorAgent] Starting formalization and implementation")

        if not hypothesis_desc:
            return {
                "error": "No hypothesis found in state.",
                "messages": ["[FactorAgent] Error: Missing hypothesis."],
            }

        # 1. Convert text to math language (Single pass)
        try:
            form_prompt = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        "You are a quantitative researcher expert in mathematics and statistics. "
                        "Convert the given financial hypothesis into a strict mathematical formula. "
                        "Clearly define each variable. "
                        "You MUST respond with valid JSON only, no markdown, no explanations.\n"
                        "CRITICAL: If the formula contains backslashes (e.g., LaTeX), you MUST double-escape them in the JSON string (e.g., \\\\alpha).",
                    ),
                    (
                        "user",
                        "Hypothesis: {hypothesis}\nRationale: {rationale}\n\n"
                        "Return ONLY valid JSON matching this exact schema:\n"
                        '{{"math_formula": "string", "variables_defined": {{"var": "definition"}}}}\n\n'
                        "Ensure ALL math symbols and formulas are correctly escaped for JSON compatibility.",
                    ),
                ]
            )
            form_chain = form_prompt | self.llm
            logger.info("[FactorAgent] LLM is formalizing the hypothesis into math...")
            raw_form_response = form_chain.invoke(
                {"hypothesis": hypothesis_desc, "rationale": rationale}
            )
            form_dict = self._parse_llm_json(raw_form_response.content)
            form_result = FormalizationOutput.model_validate(form_dict)

            logger.info(f"[FactorAgent] Formalized Math: {form_result.math_formula}")

            # 2. Implementation with Self-Correction Retry Loop
            max_retries = 2
            current_retry = 0
            code_expression = ""
            is_valid_syntax = False
            error_feedback = ""

            # Seed the conversation for implementation
            messages = [
                (
                    "system",
                    "You are an expert Qlib developer. Convert the following mathematical formula into a syntactically correct Qlib Alpha158 expression.\n\n"
                    "### SUPPORTED OPERATORS & SIGNATURES:\n"
                    f"{self.OPERATOR_SIGNATURES}\n\n"
                    "### ALLOWED DATA FIELDS:\n"
                    f"{', '.join(sorted(list(self.QLIB_FIELDS)))}\n\n"
                    "### MANDATORY RULES:\n"
                    "1. ONLY use the operators listed above. Do not assume any other operator exists.\n"
                    "2. Use $field for data fields (e.g., $close, $volume, $vwap).\n"
                    "3. Pay close attention to operator arguments (e.g., rolling windows n must be positive integers).\n"
                    "4. If a logic requires an unlisted operator, simplify it using the allowed ones.\n"
                    "5. You MUST respond with valid JSON only, no markdown, no explanations.\n"
                    "6. Ensure all characters are correctly escaped for JSON compatibility.",
                ),
                (
                    "user",
                    "Mathematical Formula: {math_formula}\nVariables: {variables}\n\n"
                    "Return ONLY valid JSON matching this exact schema:\n"
                    '{{"code_expression": "string", "is_valid_syntax": boolean}}\n\n'
                    "Ensure the JSON is correctly formatted and escaped.",
                ),
            ]

            while current_retry <= max_retries:
                if current_retry > 0:
                    logger.warning(
                        f"[FactorAgent] Retry {current_retry}/{max_retries} due to syntax error: {error_feedback}"
                    )
                    # Sliding window: only keep the base 2 messages + last retry pair to avoid
                    # unbounded token growth and prevent LangChain template variable misinterpretation.
                    # Escape any literal braces in dynamic values so LangChain's PromptTemplate
                    # does not try to interpolate them as template variables.
                    safe_code = code_expression.replace("{", "{{").replace("}", "}}")
                    safe_feedback = error_feedback.replace("{", "{{").replace("}", "}}")
                    messages = messages[:2] + [
                        (
                            "assistant",
                            f'{{{{ "code_expression": "{safe_code}", "is_valid_syntax": false }}}}',
                        ),
                        (
                            "user",
                            f"The code you generated has a syntax error: {safe_feedback}. Please FIX IT and return only the valid JSON.",
                        ),
                    ]

                impl_prompt = ChatPromptTemplate.from_messages(messages)
                impl_chain = impl_prompt | self.llm

                logger.info(
                    f"[FactorAgent] LLM is generating Qlib code (Retry {current_retry})..."
                )
                raw_impl_response = impl_chain.invoke(
                    {
                        "math_formula": form_result.math_formula,
                        "variables": str(form_result.variables_defined),
                    }
                )

                impl_dict = self._parse_llm_json(raw_impl_response.content)
                impl_result = ImplementationOutput.model_validate(impl_dict)

                code_expression = impl_result.code_expression

                # Independent validation
                is_valid, validation_msg = self._validate_qlib_expression(
                    code_expression
                )

                if is_valid:
                    # Secondary validation: Mock execution (Dry Run)
                    try:
                        from core.alphaeval.rq_eval import RiceQuantEval

                        is_mock_ok, mock_msg = RiceQuantEval.dry_run(code_expression)
                        if not is_mock_ok:
                            is_valid = False
                            validation_msg = (
                                f"Runtime Error during Mock Execution: {mock_msg}"
                            )
                    except Exception as dry_e:
                        logger.warning(f"Dry run could not be performed: {dry_e}")

                if is_valid:
                    is_valid_syntax = True
                    logger.info(
                        f"[FactorAgent] Implemented Code (Success): {code_expression}"
                    )
                    break
                else:
                    error_feedback = validation_msg
                    current_retry += 1

            if not is_valid_syntax:
                logger.error(
                    f"[FactorAgent] Failed to fix syntax after {max_retries} retries."
                )

            return {
                "math_formula": form_result.math_formula,
                "variables_defined": form_result.variables_defined,
                "code_expression": code_expression,
                "is_valid_syntax": is_valid_syntax,
                "messages": [
                    f"[FactorAgent] Math: {form_result.math_formula}",
                    f"[FactorAgent] Code: {code_expression}",
                    f"[FactorAgent] Final Valid: {is_valid_syntax}",
                ],
            }

        except Exception as e:
            logger.error(f"[FactorAgent] Failed to process factor: {e}")
            return {"error": str(e), "messages": [f"[FactorAgent] Error: {e}"]}
